no.1

create procedure sp_no1()
update DETAIL_PEMBELIAN D
     join PEMBELIAN P on D.ID_PEMBELIAN = P.ID_PEMBELIAN
     join DETAIL_BARANG db on db.ID_BARANG4 = db.ID_BARANG4
     join TOKO on db.ID_TOKO = TOKO.ID_TOKO
     set D.SUB_TOTAL = D.JUMLAH_BARANG * db.HARGA
     where P.TANGGAL between db.TANGGAL_MULAI
     and db.TANGGAL_AKHIR;

no.2

create procedure sp_n02()
update DETAIL_PEMBELIAN D
     join PEMBELIAN P on D.ID_PEMBELIAN = P.ID_PEMBELIAN
     join DETAIL_BARANG db on db.ID_BARANG4 = db.ID_BARANG4
     join TOKO on db.ID_TOKO = TOKO.ID_TOKO
     set D.SUB_TOTAL = D.JUMLAH_BARANG * db.HARGA -
     (D.SUB_TOTAL*D.DISCOUNT/100)
     where P.TANGGAL between db.TANGGAL_MULAI
     and db.TANGGAL_AKHIR;

no.3

create procedure sp_no3()
select B.ID_BARANG4, B.Nama, B.TIPE, R.RATING
     from BARANG B join REVIEW_BARANG R on B.ID_BARANG4 = R.ID_BARANG4
     where R.RATING = 5 and (B.HARGA_JUAL-B.HARGA_POKOK)>((B.HARGA_POKOK*10)/100);

no.4

CREATE DEFINER=`admin_basisdata`@`%` PROCEDURE `Soal14`()
BEGIN
SELECT DISTINCT BARANG.ID_BARANG4, BARANG.NAMA, BARANG.HARGA_JUAL, REVIEW_BARANG.RATING
FROM REVIEW_BARANG, BARANG
WHERE REVIEW_BARANG.RATING = 5
AND (BARANG.HARGA_JUAL/BARANG.HARGA_POKOK) > 10/100;
END

create view barang
SELECT DISTINCT BARANG.ID_BARANG4, BARANG.NAMA, BARANG.HARGA_JUAL, REVIEW_BARANG.RATING
  FROM REVIEW_BARANG, BARANG
  WHERE REVIEW_BARANG.RATING = 5
  AND (BARANG.HARGA_JUAL/BARANG.HARGA_POKOK) > 10/100;
